import{a as y,i as p,S as L}from"./assets/vendor-95dc692e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function c(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=c(e);fetch(e.href,s)}})();async function f(o,t){const i=`https://pixabay.com/api/?${new URLSearchParams({key:"43027284-ae8275f6d108abc1bc2578323",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"15",page:t})}`;try{return(await y.get(i)).data}catch{console.log(error)}}function h(o,t,c,i){if(o.length<=0){c.classList.add("is-hidden"),i.classList.add("is-hidden"),p.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"});return}const e=o.map(r=>`
          <li class="cards">
          <a href="${r.largeImageURL}"> <img src="${r.webformatURL}" alt="${r.tags}" width="360" height="152"/> </a>
          <div class="card-description">
            <p class="description"><b>Likes</b> ${r.likes}</p>
            <p class="description"><b>Views</b> ${r.views}</p>
            <p class="description"><b>Comments</b> ${r.comments}</p>
            <p class="description"><b>Downloads</b> ${r.downloads}</p>
            </div>
          </li>
      `).join("");t.insertAdjacentHTML("beforeend",e);const s=new L(".gallery a",{captionsData:"alt",captionDelay:250});c.classList.add("is-hidden"),i.classList.remove("is-hidden"),s.refresh()}function b(){return document.querySelector(".cards").getBoundingClientRect().height}const d=document.querySelector("#data-input"),u=document.querySelector(".gallery"),a=document.querySelector(".loader");document.querySelector(".footer-loader");const v=document.querySelector("form"),n=document.querySelector(".load-btn");let l=1,m=0;const w=15;n.classList.add("is-hidden");v.addEventListener("submit",async o=>{if(o.preventDefault(),a.classList.remove("is-hidden"),u.innerHTML="",l=1,d.value===""){p.show({title:"Error",message:"Please, fill the field to start search images. ",backgroundColor:"#ef4040",position:"topRight"});return}try{const t=await f(d.value);m=Math.ceil(t.totalHits/w),console.log(m),h(t.hits,u,a,n)}catch(t){console.log(t)}g()});n.addEventListener("click",async o=>{o.preventDefault(),a.classList.add("footer-loader"),a.classList.remove("is-hidden"),l+=1;try{const t=await f(d.value,l);h(t.hits,u,a,n)}catch(t){console.log(t)}window.scrollBy({top:b()*2,left:0,behavior:"smooth"}),g()});function g(){l>=m?(n.classList.add("is-hidden"),p.show({title:"Error",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#ef4040",position:"topRight"})):n.classList.remove("is-hidden"),a.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
